#!/bin/bash

# Script original-made by OpenA
# @ https://github.com/OpenA-forks/PotatoNV-cross-gui
#

ATTENTION="""
 THIS TOOL IS ABLSOLUTE SAFE FOR YOU DEVICE, BUT NOT FOR YOU DATA!
 AFTER UNLOCKING THE OEM, A FACTORY RESET WILL FOLLOW WITH A COMPLETE LOSS OF USERDATA.
 SO, BEFORE DOING THIS, BACK UP YOUR CONTACTS, PHOTOS, DATA APPS AND OTHERS.
 ALSO, REMOVE SD-CARDS AND MAKE A DUMP OF YOUR ORIGINAL FIRMWARE AND RECOVERY.
 IF SOMETHING GOES WRONG AND YOU GET BRICK, USE THIS TOOL BOOTFLASH FOR RESTORE IT.
"""

manifest="$PWD/bootloaders/manifest.json"
fastboot=1
test_hash=0
boot_match=
bootloader=
user_key=
fblock=

for a in "$@"; do
	case $a in
	--help | -h)
		echo ""
		echo " Command-line tool for helping Huawei device get OEM-Unlock via test-point."
		echo ""
		echo " Usage: potato-nv [-FU|-Th] [--key=%s] [--bootloader=PRA|hisiXXX]"
		echo ""
		echo "  -Bs,     --bootloader[=%s]   Select device specific bootloader for test-point mode."
		echo "  -Ht,     --hash-test         Test bootloaders .img hash sums"
		echo "  -FU,-FL, --fblock={0-1}      Write FB flag to NVE (0: Unlock 1: Lock)"
		echo "           --key=<16-chars>    Write OEM secret in to device NVE"
		echo ""
		echo "  -v,      --version           print program's version"
		echo "  -h,      --help              show this help message"
		echo ""
		echo "$ATTENTION"
		exit
		;;
	--version | -v)
		echo "potato-nv 1.1"
		exit
		;;
	--hash-test  | -Ht) test_hash=1 ;& # !! hook the next option
	--bootloader | -Bs) boot_match='puts:path' ;;
	--bootloader=*)
		bootloader=$(expr substr "$a" 14 16)
		boot_match="find:$bootloader"
		;;
	--fblock=*)
		fblock=$(expr substr "$a" 10 3)
		;;
	-FU) fblock=0 ;;
	-FL) fblock=1 ;;
	--key=*)
		user_key=$(expr substr "$a" 7 32)
		;;
	--* | -*)
		echo ""
		echo "unknown option [$a]"
		echo ""
		exit
		;;
	*)
	# ...
		;;
	esac
done

bootloader_select() {
	local loaders=()
	local count=0
	echo ""
	echo "(  If you don't know which one is yours, check here:"
	printf "\033[0;33m   https://github.com/kitsuned/PotatoNV#tested-devices  \033[0m)\n"
	echo ""
	echo "List of avilable bootloaders:"
	echo ""

	while IFS= read -r hisi; do
		loaders+=("$hisi")
		((count++))
		printf "  \033[2m[\033[0m$count\033[2m]\033[0m \033[1m$hisi\033[0m\n" #\033[2m~\033[0m\033[1;32m %s \033[0m
	done <<< "$1"
	read -p "Set the bootloader number: " i

	if [[ $i -gt $count || $i -lt 1 ]]; then
		printf "\033[0;31mNumber is out of range\033[0m\n"
		exit
	else
		bootloader="${loaders[i-1]}"
	fi
}

if [ ! -z "$boot_match" ]; then
	output=`python3 usrlock/bootloaders.py "$manifest" "$boot_match"`

	if  [ -z "$bootloader" ]; then
		bootloader_select "$output"
	elif [ -z "$output" ]; then
		echo "'$bootloader' is not found!"
		exit
	fi
	if [ $test_hash -eq 1 ]; then
		python3 usrlock/imageflasher.py "$manifest" "test:$bootloader"
		exit
	elif [ `id -u` -ne 0 ]; then
		echo "Access to '/dev/ttyUSB0' requires root:"
		(
			pkexec python3 "$PWD/usrlock/imageflasher.py" "$manifest" "$bootloader"
		)
	else
		python3 usrlock/imageflasher.py "$manifest" "$bootloader"
	fi
	read -p "Connecting to fastboot? (y/n) " y
	if [[ "$y" != 'Y' && "$y" != 'y' ]]; then
		exit
	fi
fi

if [ $fastboot -eq 1 ]; then
	python3 usrlock/fastboot.py "$user_key" "$fblock"
fi
